In [1]:
###  tell me the library you use ? ( 10 to 15 name to tell them)
###  why you use the numpy ?
###  learn 10 to 15 name of library!
###  numpy is (to reshape the data ! ) 
#### what is difference between shallow copy deep copy?

In [39]:
import numpy as np

In [9]:
arr1=np.array([])
arr1

array([], dtype=float64)

In [11]:
ya_list = [10,20,30,40,50,60]
print(ya_list)
type(ya_list)

[10, 20, 30, 40, 50, 60]


list

In [13]:
a= np.array(ya_list)
print(a)
type(a)

[10 20 30 40 50 60]


numpy.ndarray

In [15]:
a.ndim

1

In [17]:
a.size

6

In [19]:
a.shape 

(6,)

In [21]:
my_matrix = [[1,2,3,4,],[5,6,7,8],[9,10,11,12]]   #### image processing are use in matrix 
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [23]:
b=np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b.ndim

2

In [29]:
b.size

12

In [31]:
b.shape

(3, 4)

In [33]:
b.dtype

dtype('int32')

In [35]:
type(b)

numpy.ndarray

In [148]:
arr1=np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [41]:
arr1.ndim


3

In [43]:
arr1.size

12

In [45]:
arr1.shape 

(2, 2, 3)

### built in method

In [54]:
arr2=arr1.reshape((1,3,4))

In [56]:
arr2.shape

(1, 3, 4)

In [58]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

### arange 

In [63]:
np.arange(15)  #### end, default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [67]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zero and ones 

In [72]:
import numpy as np

In [74]:
np.zeros(3)

array([0., 0., 0.])

In [76]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
np.ones(1)

array([1.])

In [86]:
np.ones(3)

array([1., 1., 1.])

In [88]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linespace

# Return evenly spaced number over a specified Interval.


In [96]:
import numpy as np


In [100]:
np.linspace(1,15) ## print default 50 va

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [106]:
np.linspace(40,115)

array([ 40.        ,  41.53061224,  43.06122449,  44.59183673,
        46.12244898,  47.65306122,  49.18367347,  50.71428571,
        52.24489796,  53.7755102 ,  55.30612245,  56.83673469,
        58.36734694,  59.89795918,  61.42857143,  62.95918367,
        64.48979592,  66.02040816,  67.55102041,  69.08163265,
        70.6122449 ,  72.14285714,  73.67346939,  75.20408163,
        76.73469388,  78.26530612,  79.79591837,  81.32653061,
        82.85714286,  84.3877551 ,  85.91836735,  87.44897959,
        88.97959184,  90.51020408,  92.04081633,  93.57142857,
        95.10204082,  96.63265306,  98.16326531,  99.69387755,
       101.2244898 , 102.75510204, 104.28571429, 105.81632653,
       107.34693878, 108.87755102, 110.40816327, 111.93877551,
       113.46938776, 115.        ])

In [118]:
np.linspace(0,100,11,retstep=True) #### 

(array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]),
 10.0)

# eye

In [123]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.eye(5) ## generate 2d array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## use copy function 

In [150]:
arr1= arr2
arr1

array([[[30, 30, 30],
        [30, 30, 30]],

       [[30, 30, 30],
        [30, 30, 30]]])

In [152]:
arr2[:10]=30
arr2

array([[[30, 30, 30],
        [30, 30, 30]],

       [[30, 30, 30],
        [30, 30, 30]]])

In [144]:

arr1

array([[[30, 30, 30],
        [30, 30, 30]],

       [[30, 30, 30],
        [30, 30, 30]]])

In [1]:
arr1=[1,2,3,4]
arr2=[5,6,7,8] 

In [7]:
arr2 =arr1

In [9]:
copy =arr1.copy()


In [25]:
arr2[:10]=30
arr2

TypeError: can only assign an iterable

In [21]:
arr1

[1, 2, 3, 4]

In [27]:
arr2

[1, 2, 3, 4]

In [29]:
copy

[1, 2, 3, 4]

In [41]:
arr1=np.array([])
my_arr=[1,2,3,4,5,6,7,8,9,0]
a =np.array(my_arr)


## random

In [44]:
np.random.rand()


0.5760153230410205

In [47]:
np.random.rand(18)


array([0.70084648, 0.57344846, 0.26721105, 0.30281942, 0.00377387,
       0.49799983, 0.2029992 , 0.53863849, 0.60245422, 0.94221143,
       0.56726291, 0.58201318, 0.03611391, 0.6305072 , 0.72063304,
       0.39187034, 0.98021426, 0.97330493])

In [53]:
np.random.rand(10).reshape((2,5))


array([[0.41367602, 0.25198446, 0.20593088, 0.45875847, 0.73936082],
       [0.41292524, 0.62654855, 0.90854902, 0.93695109, 0.89482717]])

# randn

In [62]:
arr1=np.random.randn(50)
arr1

array([ 0.68542424,  0.36036403,  2.44611869,  0.9730237 ,  0.72633006,
        0.98450846, -0.05812805,  0.52019535,  1.67381949,  0.49259049,
        0.72200247, -0.52241802, -0.72075573, -0.2393491 , -0.6033766 ,
        0.74295457, -0.30705023, -0.08571629, -0.13633099, -0.0880057 ,
       -3.15559495,  0.09864867, -0.18944808, -1.8798175 ,  2.2627881 ,
        0.24520016, -0.97571345, -1.55869867, -0.64221515,  1.21273884,
        0.46053136,  2.05109393,  1.03321594,  2.129912  ,  0.07387947,
        0.5381299 , -0.99263571, -0.22583782, -0.73694863, -1.59373331,
        0.098119  , -0.56722089,  0.160479  ,  0.10155428,  0.46497994,
        1.44850369,  0.44167056,  0.13688834, -1.42857359, -1.66785707])

# randint

In [73]:
np.random.randint(1,100)


21

In [75]:
np.random.randint(1,100,10)


array([81, 17, 34, 40, 81, 78, 72, 94, 98, 60])

In [79]:
np.random.randint(10,20,30)


array([14, 18, 13, 15, 13, 14, 12, 16, 19, 19, 15, 18, 13, 18, 19, 19, 12,
       15, 10, 19, 18, 16, 13, 14, 13, 12, 16, 11, 12, 14])